### ISSUE TITLE
RSA.generate() have error on android 4.3

### ISSUE THREAD

**Issue by bodaghialib4** [amitaymolko/react-native-rsa-native#32] opened 2018-03-17 13:50 UTC
I used RSA.generate() in iOS 11 and android 6.0 and work correctly. but in android 4.3 I get an error that say:

![screenshot_2018-03-17-17-17-39](https://user-images.githubusercontent.com/23075818/37556173-63c711e4-2a07-11e8-87cf-8652b726b235.png)

**Comment by bodaghialib4** [comment] 2018-04-04 04:55
@amitaymolko @crafterm

I will be very grateful if you have solution for my problem.

**Comment by amitaymolko** [comment] 2018-04-04 17:56
I see keychain support for 4.3+ 
Regular encryption support for pre 6.0 is missing, I'll try to write it up over the weekend

**Comment by amitaymolko** [comment] 2018-04-07 07:12
@bodaghialib4 I have pushed a fix for Charsets in android 4.3, I'm not sure if its the same issue you are having.
Please update to version `1.0.20`, if you still experience the same issue please post back with exact android model and version.

**Comment by bodaghialib4** [comment] 2018-04-28 10:41
@amitaymolko thanks a lot for your response. but after updating my version I get the same error and not fixed.

my react-native version is: 0.51.0

my device model is: 
       HUAWEI Ascend
       model: G630-U10
       android version: 4.3.0

**Comment by amitaymolko** [comment] 2018-04-30 06:27
@bodaghialib4 
I still haven't been able to recreate the issue, I'm testing on simulators.
Do you have another 4.3 device you can test on? 
I want to figure out if the issue is with the device or android version.

**Comment by amitaymolko** [comment] 2019-08-07 07:08
closing due to inactivity

**Closed by amitaymolko** 2019-08-07 07:08 UTC
